### ISSUE TITLE
doc: 更新徽标，增加 3.11 测试支持

### ISSUE THREAD

**Issue by whg517** [whg517/fastapi-sa#2]
Codacy 

```
[![Codacy Badge](https://app.codacy.com/project/badge/Grade/c76cfa7d7d274f899967019900465403)](https://www.codacy.com/gh/whg517/fastapi-sa/dashboard?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=whg517/fastapi-sa&amp;utm_campaign=Badge_Grade)
```

Codecov

```
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          flags: unittests
          verbose: true
```
